### ISSUE TITLE
repeater error with newest build of zion builder pro

### ISSUE THREAD

**Issue by bennimen** [zionbuilder/zionbuilder#576]
Hello all,

I just bought the zion builder pro deal and am getting this error with 2.7.1.

> Notice: Trying to get property 'options' of non-object in /var/www/vhosts/thisismysite.com/httpdocs/wp-content/plugins/zionbuilder-pro/includes/Repeater.php on line 138
> 
> Fatal error: Uncaught Error: Call to a member function get_value() on null in /var/www/vhosts/thisismysite.com/httpdocs/wp-content/plugins/zionbuilder-pro/includes/Repeater.php:138 Stack trace: #0 /var/www/vhosts/thisismysite.com/httpdocs/wp-content/plugins/zionbuilder-pro/includes/Repeater.php(132): ZionBuilderPro\Repeater::is_repeater_provider() #1 /var/www/vhosts/thisismysite.com/httpdocs/wp-includes/class-wp-hook.php(303): ZionBuilderPro\Repeater->maybe_change_element_renderer() #2 /var/www/vhosts/thisismysite.com/httpdocs/wp-includes/plugin.php(189): WP_Hook->apply_filters() #3 /var/www/vhosts/thisismysite.com/httpdocs/wp-content/plugins/zionbuilder/includes/Elements/Element.php(719): apply_filters() #4 /var/www/vhosts/thisismysite.com/httpdocs/wp-content/plugins/zionbuilder/includes/Renderer.php(84): ZionBuilder\Elements\Element->render_element() #5 /var/www/vhosts/thisismysite.com/httpdocs/wp-content/plugins/zionbuilder/includes/Renderer.php(70): ZionBuilder\Renderer->render_element() #6 /var/www/vhosts/maui in /var/www/vhosts/thisismysite.com/httpdocs/wp-content/plugins/zionbuilder-pro/includes/Repeater.php on line 138
> There has been a critical error on this website.
> 
> Learn more about troubleshooting WordPress.
> 

I downgraded to 2.7.0

Anyone else getting this?

**Comment by bennimen** [comment]
Quick update: 

going back to plugins 2.7.0 builder and builder pro stopped the error from showing up.

**Comment by zauan** [comment]
hi there,

sorry to see that you are encountering problems. I will investigate this error and get back to you. It will also be resolved in the update that we will release this week.

Best regards,
Stefan

**Comment by zauan** [comment]
Hi there,

After further investigations, this error should only appear if you have different free and PRO versions. Can you please make sure that both the free and PRO are at 2.7.1?

**Comment by zauan** [comment]
Closing due to inactivity. If this occurs in v2.7.2 which will be released this week, please reopen the ticket for further investigations
